### ISSUE TITLE
请问目前该解决方法的实际使用情况

### ISSUE THREAD

**Issue by lidianhao123** [peunzhang/pageResponse#8]
浏览了当前解决方案，感觉不错，请问通过缩放来进行适配是否会影响内容元素动画的性能

**Comment by peunzhang** [comment]
使用css3合成属性transform:scale来完成缩放的，高端设备动画性能方面没有问题的
http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

**Comment by lidianhao123** [comment]
我想了解一下，这种适配方案在各种安卓设备上的情况如何？（暂不考虑低端安卓设备）

**Comment by peunzhang** [comment]
android2.3.5以上都支持，暂无遇到问题

**Comment by lidianhao123** [comment]
非常感谢您的回复，我能再多问一下，请问您提到的Android2.3.5 以上都支持，大概是什么规模的测试来支持您的这个结论。我们最近在研究合适的适配方案，看到您这个方案挺不错的，但是心里有些没底，想多了解一下。

**Comment by peunzhang** [comment]
就从我们团队有的测试机和产品同事的手机，大概20来部android操作系统，覆盖小米、三星、华为、魅族、联想等

**Comment by erdongjun** [comment]
最近有开始了解移动端的px布局，感谢！！

**Comment by q215171650** [comment]
请问下作者页面宽度已知，高度不固定，如何设置参数里height

**Comment by akan** [comment]
用过一次局部transform,联想手机transform scale,文字没有同步transform，或者就是取整不对误差很大。楼主确认经过广泛测试？

**Comment by lidianhao123** [comment]
long long time, close it!
